name: CI

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Setup Node.js version
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint to check code quality
      - name: Run ESLint
        run: npm run lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: npm run test

      # Run End-to-End Tests
      - name: Run End-to-End Tests
        run: npm run test:e2e

      # Run Test Coverage
      - name: Run Test Coverage
        run: npm run test:cov
